// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Measurement struct {
	ID              uuid.UUID
	MeasurementTime time.Time
	Humidity        float64
	Temperature     float64
}
